version: '3.9'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "256m"
    max-file: "1"

networks:
  default:
    name: phpfpm-test
    driver: bridge

services:
  nginx:
    image: wp-nginx:1.0
    container_name: nginx
    build:
      context: ./src/nginx
    ports:
      - 8080:8080
    depends_on:
      - phpfpm
    logging: *logging

  phpfpm:
    image: phpfpm:1.0
    container_name: phpfpm
    build:
      context: ./src/php-fpm
    ports:
      - 9000
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_PROTOCOL
      - OTEL_PHP_AUTOLOAD_ENABLED
      - OTEL_PROPAGATORS
      - OTEL_SERVICE_NAME
    logging: *logging
  
  jaeger:
    image: jaegertracing/all-in-one:1.44
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317
      - 4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    logging: *logging
