version: '3.9'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "256m"
    max-file: "1"

networks:
  default:
    name: wp-test
    driver: bridge

services:
  nginx:
    image: wp-nginx:1.0
    container_name: nginx
    build:
      context: ./src/nginx
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
    depends_on:
      - wpfpm
    logging: *logging

  wpfpm:
    image: wp-fpm:1.0
    container_name: wpfpm
    build:
      context: ./src/wordpress
    ports:
      - 9000
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_PROTOCOL
      - OTEL_PHP_AUTOLOAD_ENABLED
      - OTEL_PROPAGATORS
      - OTEL_SERVICE_NAME
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_USER
      - WP_EMAIL
      - WP_PASSWORD
      - WP_TITLE
      - WP_USERNAME
      - WP_URL
    depends_on:
      mysql:
        condition: service_healthy
    logging: *logging

  mysql:
    image: mysql:5.7
    container_name: ${DB_NAME}
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    logging: *logging
  
  jaeger:
    image: jaegertracing/all-in-one:1.44
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317
      - 4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    logging: *logging
